#!/bin/bash
# ============================================================================
# Stage 4: TRACULA — Tract-specific Analysis with FreeSurfer
# ============================================================================
# TRACULA (TRActs Constrained by UnderLying Anatomy) uses:
#   - FreeSurfer cortical/subcortical segmentation as anatomical priors
#   - FSL's bedpostx ball-and-stick model for local fiber orientations
#   - Bayesian framework to reconstruct 42 major white matter pathways
#
# This is the SOTA for tract-specific analysis that leverages both
# FreeSurfer and FSL (FDT) together.
#
# Runtime: ~2-4 hours per subject
# ============================================================================

set -euo pipefail
source "$(dirname "$0")/00_setup_env.sh"

SUBJECT="${1:?Usage: $0 <subject_id>}"
ACQ="${2:-CHARMED}"

DWI_DIR="${WAND_DERIVATIVES}/fsl/${SUBJECT}/ses-02/dwi"
TRACULA_DIR="${WAND_DERIVATIVES}/tracula"
mkdir -p "${TRACULA_DIR}"

echo "=== TRACULA: ${SUBJECT} ==="

# ---------------------------------------------------------------
# Step 1: Create TRACULA configuration file
# ---------------------------------------------------------------

CONFIG="${TRACULA_DIR}/${SUBJECT}_dmrirc"

cat > "${CONFIG}" << DMRIRC
# TRACULA configuration for WAND ${SUBJECT}
# Generated by neurojax processing pipeline

# FreeSurfer SUBJECTS_DIR
setenv SUBJECTS_DIR ${SUBJECTS_DIR}

# Subject list
set dtroot = ${TRACULA_DIR}
set subjlist = (${SUBJECT})

# Input DWI
set dcmroot = ${DWI_DIR}
set dcmlist = (${ACQ}_eddy.nii.gz)

# Acquisition parameters
set bvalfile = (${DWI_DIR}/${ACQ}_bedpostx_input/bvals)
set bvecfile = (${DWI_DIR}/${ACQ}_bedpostx_input/bvecs)

# Use existing eddy-corrected data (skip TRACULA's own preprocessing)
set dession = 0
set doeddy = 0
set dorotbvecs = 0

# Registration
set doregflt = 1
set doregbbr = 1
set doregmni = 1
set doregcvs = 0

# bedpostx (use existing if available)
set usemaskanat = 1
set pathlist = (lh.cst_AS rh.cst_AS \
                lh.unc_AS rh.unc_AS \
                lh.ilf_AS rh.ilf_AS \
                fmajor_PP fminor_PP \
                lh.atr_PP rh.atr_PP \
                lh.ccg_PP rh.ccg_PP \
                lh.cab_PP rh.cab_PP \
                lh.slfp_PP rh.slfp_PP \
                lh.slft_PP rh.slft_PP \
                lh.slf1_AS rh.slf1_AS \
                lh.slf2_AS rh.slf2_AS \
                lh.slf3_AS rh.slf3_AS)

# Number of control points per path
set ncpts = (6 6 \
             5 5 \
             7 7 \
             7 5 \
             5 5 \
             5 5 \
             4 4 \
             7 7 \
             5 5 \
             5 5 \
             5 5 \
             5 5)
DMRIRC

echo "TRACULA config written to ${CONFIG}"

# ---------------------------------------------------------------
# Step 2: TRACULA preprocessing (registration only, DWI already done)
# ---------------------------------------------------------------

echo "Running TRACULA prep (registration)..."
trac-all -prep -c "${CONFIG}"

# ---------------------------------------------------------------
# Step 3: TRACULA bedpostx (or use existing)
# ---------------------------------------------------------------

BPX_DIR="${DWI_DIR}/${ACQ}.bedpostX"
TRACULA_BPX="${TRACULA_DIR}/${SUBJECT}/dmri.bedpostX"

if [ -d "${BPX_DIR}" ] && [ ! -d "${TRACULA_BPX}" ]; then
    echo "Linking existing bedpostx results..."
    ln -sf "${BPX_DIR}" "${TRACULA_BPX}"
else
    echo "Running TRACULA bedpostx..."
    trac-all -bedp -c "${CONFIG}"
fi

# ---------------------------------------------------------------
# Step 4: TRACULA path reconstruction
# ---------------------------------------------------------------

echo "Running TRACULA path reconstruction..."
trac-all -path -c "${CONFIG}"

# ---------------------------------------------------------------
# Step 5: Extract tract statistics
# ---------------------------------------------------------------

echo "Extracting tract statistics..."
trac-all -stat -c "${CONFIG}"

# Overall stats table
tractstats2table \
    --inputs "${TRACULA_DIR}/${SUBJECT}/dpath/"*"/pathstats.overall.txt" \
    --overall \
    --tablefile "${TRACULA_DIR}/${SUBJECT}_tractstats.csv"

echo "=== TRACULA complete for ${SUBJECT} ==="
echo "Results: ${TRACULA_DIR}/${SUBJECT}/"
echo "Stats:   ${TRACULA_DIR}/${SUBJECT}_tractstats.csv"
