#!/bin/bash
# ============================================================================
# Stage QC: Quality Control — MRIQC + FreeSurfer QC + FSL QC
# ============================================================================
# Run BEFORE analysis to flag bad data. Three QC tiers:
#
# 1. MRIQC (via Neurodesk): automated quality metrics for all raw inputs
#    - T1w, T2w: SNR, CNR, WM/GM contrast, INU, EFC
#    - BOLD: tSNR, DVARS, FD, outlier fraction, GCOR
#    - DWI: eddy_quad QC (already in 02_dwi_preproc.sh)
#
# 2. FreeSurfer QC: post-recon-all quality assessment
#    - Euler number (topological defects — lower is better)
#    - Surface area, cortical thickness, volume stats
#    - Talairach QC
#    - Recommended by FS team: visual inspection + euler + outlier detection
#
# 3. FSL FEAT/MELODIC reports: already generated by 19_fmri_processing.sh
#    - Motion plots, registration overlays, ICA component maps
#
# Run this EARLY in the pipeline — on raw data + after recon-all.
# ============================================================================

set -euo pipefail
source "$(dirname "$0")/00_setup_env.sh"

SUBJECT="${1:?Usage: $0 <subject_id>}"

QC_DIR="${WAND_DERIVATIVES}/qc/${SUBJECT}"
mkdir -p "${QC_DIR}/mriqc" "${QC_DIR}/freesurfer" "${QC_DIR}/summary"

echo "=== Quality Control: ${SUBJECT} ==="

# ---------------------------------------------------------------
# 1. MRIQC — Input data quality (via Neurodesk or Docker)
# ---------------------------------------------------------------

echo ""
echo "--- MRIQC ---"

# Check if MRIQC is available (Neurodesk or Docker)
if command -v mriqc 2>/dev/null || docker images 2>/dev/null | grep -q mriqc; then
    echo "Running MRIQC on structural and functional data..."

    # Run via command line (adjust for Neurodesk container invocation)
    mriqc "${WAND_ROOT}" "${QC_DIR}/mriqc" \
        participant \
        --participant-label "${SUBJECT#sub-}" \
        --nprocs ${OMP_NUM_THREADS} \
        --no-sub \
        -w "${QC_DIR}/mriqc/work" 2>&1 | tail -5 || \
    echo "  MRIQC failed or not available. Install via Neurodesk."

    echo "  MRIQC report: ${QC_DIR}/mriqc/"
else
    echo "  MRIQC not available. Install via Neurodesk:"
    echo "    neurodesk run mriqc:24.0.0 -- mriqc ..."
    echo "  Or Docker:"
    echo "    docker run nipreps/mriqc:24.0.0 ..."
fi

# ---------------------------------------------------------------
# 2. FreeSurfer QC — Post-recon-all assessment
# ---------------------------------------------------------------

echo ""
echo "--- FreeSurfer QC ---"

FS_DIR="${SUBJECTS_DIR}/${SUBJECT}"

if [ -f "${FS_DIR}/scripts/recon-all.done" ]; then
    echo "recon-all completed. Running QC..."

    # 2a. qatools.py — FreeSurfer's official QC tool
    # Computes: WM/GM SNR, holes, defects, CC size, Talairach rotation,
    #           contrast SNR. Generates screenshots and fornix QC.
    echo "  Running qatools.py (screenshots + fornix + metrics)..."
    qatools.py \
        --subjects_dir "${SUBJECTS_DIR}" \
        --output_dir "${QC_DIR}/freesurfer" \
        --subjects "${SUBJECT}" \
        --screenshots \
        --fornix 2>&1 | tail -5
    echo "  qatools output: ${QC_DIR}/freesurfer/"
    echo "  Screenshots: ${QC_DIR}/freesurfer/screenshots/"
    echo "  Fornix QC: ${QC_DIR}/freesurfer/fornix/"
    echo "  Metrics CSV: ${QC_DIR}/freesurfer/qatools_*.csv"

    # 2b. Euler number (topological defects — key quality indicator)
    echo "  Euler number (lower magnitude = better surface quality):"
    for HEMI in lh rh; do
        EULER=$(mris_euler_number "${FS_DIR}/surf/${HEMI}.orig.nofix" 2>&1 | grep "euler" | tail -1 || echo "?")
        echo "    ${HEMI}: ${EULER}"
        echo "${HEMI}_euler=${EULER}" >> "${QC_DIR}/freesurfer/euler.txt"
    done

    # 2c. Talairach QC
    echo "  Talairach registration QC..."
    talairach_afd -T 0.005 -xfm "${FS_DIR}/mri/transforms/talairach.xfm" 2>&1 | tail -1 | tee "${QC_DIR}/freesurfer/talairach_qc.txt"

    # 2d. Volume and surface statistics tables
    echo "  Extracting volume and surface statistics..."
    asegstats2table \
        --subjects "${SUBJECT}" \
        --meas volume \
        --tablefile "${QC_DIR}/freesurfer/aseg_volumes.csv" \
        --sd "${SUBJECTS_DIR}" 2>&1 | tail -1

    for HEMI in lh rh; do
        for MEAS in thickness area volume; do
            aparcstats2table \
                --subjects "${SUBJECT}" \
                --hemi ${HEMI} \
                --meas ${MEAS} \
                --tablefile "${QC_DIR}/freesurfer/${HEMI}_aparc_${MEAS}.csv" \
                --sd "${SUBJECTS_DIR}" 2>&1 | tail -1
        done
    done

    # 2e. Brain volume summary
    python3 << 'PYEOF'
import os, json
import numpy as np

fs_dir = os.environ.get('FS_DIR', '')
qc_dir = os.environ.get('QC_DIR', '') + '/freesurfer'

# Read aseg stats
stats_file = os.path.join(fs_dir, 'stats', 'aseg.stats')
if os.path.exists(stats_file):
    summary = {}
    with open(stats_file) as f:
        for line in f:
            if line.startswith('# Measure'):
                parts = line.strip().split(',')
                if len(parts) >= 4:
                    name = parts[1].strip()
                    value = parts[3].strip()
                    summary[name] = value

    print("  Brain volume summary:")
    for key in ['BrainSeg', 'BrainSegNotVent', 'CortexVol', 'SubCortGrayVol',
                'TotalGray', 'CerebralWhiteMatterVol', 'EstimatedTotalIntraCranialVol']:
        if key in summary:
            print(f"    {key}: {summary[key]}")

    with open(os.path.join(qc_dir, 'brain_volumes.json'), 'w') as f:
        json.dump(summary, f, indent=2)
PYEOF

    echo "  FreeSurfer QC: ${QC_DIR}/freesurfer/"
else
    echo "  recon-all not complete. Run 01_freesurfer_recon.sh first."
fi

# ---------------------------------------------------------------
# 3. Summary report
# ---------------------------------------------------------------

echo ""
echo "--- QC Summary ---"

python3 << 'PYEOF'
import os, json

qc_dir = os.environ.get('QC_DIR', '') + '/summary'
subject = os.environ.get('SUBJECT', '')

summary = {'subject': subject, 'qc_status': 'PENDING'}

# Check Euler numbers
euler_file = os.environ.get('QC_DIR', '') + '/freesurfer/euler.txt'
if os.path.exists(euler_file):
    with open(euler_file) as f:
        for line in f:
            if '=' in line:
                key, val = line.strip().split('=')
                summary[key] = int(val) if val.lstrip('-').isdigit() else val

    # Flag if Euler number is very negative (bad topology)
    lh_euler = summary.get('lh_euler', 0)
    rh_euler = summary.get('rh_euler', 0)
    if isinstance(lh_euler, int) and isinstance(rh_euler, int):
        avg_euler = (abs(lh_euler) + abs(rh_euler)) / 2
        if avg_euler > 100:
            summary['qc_status'] = 'FLAG: high Euler number (bad surface topology)'
            print(f"  ⚠ HIGH EULER NUMBER: lh={lh_euler}, rh={rh_euler}")
        else:
            summary['qc_status'] = 'PASS'
            print(f"  ✓ Euler numbers OK: lh={lh_euler}, rh={rh_euler}")

with open(os.path.join(qc_dir, 'qc_summary.json'), 'w') as f:
    json.dump(summary, f, indent=2)

print(f"  QC summary: {qc_dir}/qc_summary.json")
PYEOF

echo ""
echo "=== QC complete for ${SUBJECT} ==="
