#!/usr/bin/env python
"""Re-test the WAND band irreversibility against a SOTA reversible surrogate null.

The committed irreversibility (``wand_band_langevin.py`` / ``wand_timefreq_irrev.py``)
was significant vs a *time-shuffle* null — which whitens the spectrum, so it only
rejects i.i.d. noise.  This re-tests the band circulation (the whitened Lévy area /
``circulation_strength``, the rough-path twin of the Langevin α*) against a proper
**reversible, spectrum- and marginal-matched** null generated by the
TimeseriesSurrogates.jl oracle (per-channel IAAFT): each surrogate preserves every
channel's power spectrum *and* amplitude distribution exactly and is time-reversible,
so surviving circulation cannot be attributed to the autocorrelation/spectrum or the
(skewed) envelope marginal — only to genuine broken detailed balance.

Caveat: per-channel IAAFT removes cross-coupling, so this is the reversible
*matched-spectrum* null; the antisymmetric/whitened circulation is insensitive to
symmetric coupling, so the floor is fair.  The stricter coupling-preserving null is
the constrained-randomization (TISEAN) follow-up.

    WAND_OUT=/data/datasets/wand_src PYTHONPATH=src \\
      .venv-models/bin/python scripts/real_data/wand_reversible_null.py
"""

import os
import subprocess

import jax
import jax.numpy as jnp
import numpy as np

from neurojax.analysis.timefreq import morlet_cwt, eeglab_cycles
from neurojax.dynamics import svht_rank, circulation_strength

OUT = os.environ.get("WAND_OUT", "/data/datasets/wand_src")
SCR = os.environ.get("SCRATCH", "/tmp/claude-1000/-home-mhough-dev-neurojax/"
                     "a44a9232-d44b-4b8b-8812-560682c446fa/scratchpad")
ORACLE = os.path.join(os.path.dirname(__file__), "oracle_surrogates")
JULIA = os.path.expanduser("~/.juliaup/bin/julia")
FS = 250.0
BANDS = {"delta": (2, 4), "theta": (4, 8), "alpha": (8, 13),
         "beta": (13, 30), "gamma": (30, 45)}
ENV_FS = 50.0
RANK_CAP = 24
N_SURR = int(os.environ.get("N_SURR", "60"))


def band_embedding(X, lo, hi):
    fc = jnp.linspace(lo, hi, 6)
    C = morlet_cwt(jnp.asarray(X.T), FS, fc, eeglab_cycles(fc, 3.0, 0.5))
    env = np.asarray(jnp.mean(jnp.abs(C), axis=1))
    ds = int(FS / ENV_FS)
    env = env[:, : (env.shape[1] // ds) * ds].reshape(68, -1, ds).mean(2)
    env = env - env.mean(1, keepdims=True)
    r = min(int(svht_rank(env)), RANK_CAP)
    U, s, _ = np.linalg.svd(env, full_matrices=False)
    return ((U[:, :r].T @ env).T).astype(np.float64), r


def whitened_circulation(Z, dt):
    """Scale-free net circulation: whiten by own covariance, then ‖levy_rate‖."""
    Zc = Z - Z.mean(0)
    w, V = np.linalg.eigh(np.cov(Zc.T))
    Wh = V @ np.diag(1.0 / np.sqrt(np.clip(w, 1e-9, None))) @ V.T
    return float(circulation_strength(jnp.asarray(Zc @ Wh), dt))


def oracle_surrogates(Z, n, seed):
    """Call the TimeseriesSurrogates.jl oracle -> (n, T, r) IAAFT surrogates."""
    fin = os.path.join(SCR, "rn_in.npy")
    fout = os.path.join(SCR, "rn_out.npy")
    np.save(fin, Z)
    env = dict(os.environ, JULIA_PROJECT=ORACLE)
    subprocess.run([JULIA, "--startup-file=no",
                    os.path.join(ORACLE, "gen_surrogates.jl"),
                    fin, fout, str(n), "iaaft", str(seed)],
                   check=True, env=env, capture_output=True)
    return np.load(fout)


def main():
    print("JAX backend:", jax.default_backend())
    X = np.load(os.path.join(OUT, "parcels68.npy")).astype(np.float32)
    print(f"raw source parcels: {X.shape} @ {FS:.0f} Hz; N_surr={N_SURR}")
    dt = 1.0 / ENV_FS

    print(f"\n=====  WAND band circulation vs SOTA reversible (IAAFT) null  =====")
    print(f"{'band':>7} {'rank':>5} {'circ':>9} {'null':>9} {'null_sd':>8} "
          f"{'z':>7} {'p':>7}")
    for name, (lo, hi) in BANDS.items():
        Z, r = band_embedding(X, lo, hi)
        obs = whitened_circulation(Z, dt)
        S = oracle_surrogates(Z, N_SURR, 0)
        sur = np.array([whitened_circulation(S[i], dt) for i in range(len(S))])
        z = (obs - sur.mean()) / (sur.std() + 1e-12)
        p = (np.sum(sur >= obs) + 1) / (len(sur) + 1)
        print(f"{name:>7} {r:>5d} {obs:>9.4f} {sur.mean():>9.4f} {sur.std():>8.4f} "
              f"{z:>7.2f} {p:>7.3f}")
    print("  -> circ above a spectrum+marginal-matched, time-reversible null ⇔ genuine")
    print("     broken detailed balance (not autocorrelation, spectrum, or envelope skew).")


if __name__ == "__main__":
    main()
