"""Side-by-side comparison: neurojax GaussianHMM vs osl-dynamics HMM.

Loads the same synthetic data generated by osl-dynamics, runs the neurojax
HMM, loads the osl-dynamics baseline results (from the oracle container),
and produces quantitative + visual comparison.

Prerequisites:
    # 1. Generate data & run osl-dynamics baseline in container:
    docker run --gpus all --ipc=host -v $(pwd)/data:/data \
        neurojax/oracle-osl python /scripts/generate_synthetic.py
    docker run --gpus all --ipc=host -v $(pwd)/data:/data \
        -e N_EPOCHS=20 neurojax/oracle-osl python /scripts/run_hmm_baseline.py

    # 2. Run this script:
    python examples/compare_hmm_osl.py
"""

import json
import time

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import linear_sum_assignment

from neurojax.models.hmm import GaussianHMM


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def hungarian_match(true_labels, pred_labels, n_states):
    """Find optimal state permutation via Hungarian algorithm."""
    cost = np.zeros((n_states, n_states))
    for i in range(n_states):
        for j in range(n_states):
            cost[i, j] = -np.sum((true_labels == i) & (pred_labels == j))
    _, col_ind = linear_sum_assignment(cost)
    return col_ind  # col_ind[pred] -> true


def remap_states(labels, mapping):
    """Apply a permutation mapping to state labels."""
    return np.array([mapping[s] for s in labels])


def dice_per_state(true_oh, pred_oh, n_states):
    """Per-state Dice coefficient (soft overlap)."""
    dice = []
    for s in range(n_states):
        intersection = np.sum(true_oh[:, s] * pred_oh[:, s])
        union = np.sum(true_oh[:, s]) + np.sum(pred_oh[:, s])
        dice.append(2 * intersection / (union + 1e-10))
    return np.array(dice)


def correlation_matrix(A, B):
    """Element-wise Pearson correlation between two matrices."""
    return np.corrcoef(A.ravel(), B.ravel())[0, 1]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("  neurojax vs osl-dynamics HMM Comparison")
    print("=" * 60)

    # Load ground truth
    ts = np.load("data/osl_sim_timeseries.npy")
    true_states_oh = np.load("data/osl_sim_states_true.npy")
    true_means = np.load("data/osl_sim_means_true.npy")
    true_covs = np.load("data/osl_sim_covs_true.npy")
    true_hard = np.argmax(true_states_oh, axis=1)
    n_states = true_states_oh.shape[1]
    n_channels = ts.shape[1]

    print(f"\nData: {ts.shape}  |  {n_states} states, {n_channels} channels")

    # Load osl-dynamics baseline
    osl_gamma = np.load("data/osl_baseline/gamma.npy")
    osl_means = np.load("data/osl_baseline/means.npy")
    osl_covs = np.load("data/osl_baseline/covariances.npy")
    osl_trans = np.load("data/osl_baseline/trans_prob.npy")
    with open("data/osl_baseline/config.json") as f:
        osl_config = json.load(f)
    osl_time = osl_config.get("elapsed_seconds", "?")

    # osl-dynamics may truncate due to sequence_length batching
    T_osl = osl_gamma.shape[0]
    print(f"osl-dynamics gamma: {osl_gamma.shape}  (trained in {osl_time:.1f}s)")

    # ---- Run neurojax HMM ----
    data_jax = [jnp.array(ts)]
    model = GaussianHMM(n_states=n_states, n_channels=n_channels)

    print("\nFitting neurojax HMM (20 epochs)...")
    t0 = time.time()
    history = model.fit(data_jax, n_epochs=20)
    nj_time = time.time() - t0
    print(f"neurojax training: {nj_time:.1f}s")

    nj_gamma = np.array(model.infer(data_jax)[0])
    nj_means = np.array(model.state_means)
    nj_covs = np.array(model.state_covariances)
    nj_trans = np.array(model.transition_matrix)

    # ---- Align states (Hungarian matching vs ground truth) ----
    osl_hard = np.argmax(osl_gamma, axis=1)
    nj_hard = np.argmax(nj_gamma, axis=1)

    # Match against true states (use common length)
    T_common = min(len(true_hard), T_osl, len(nj_hard))

    osl_perm = hungarian_match(true_hard[:T_common], osl_hard[:T_common], n_states)
    nj_perm = hungarian_match(true_hard, nj_hard, n_states)

    osl_remapped = remap_states(osl_hard[:T_common], osl_perm)
    nj_remapped = remap_states(nj_hard, nj_perm)

    # ---- Metrics ----
    print("\n" + "-" * 60)
    print("  RESULTS")
    print("-" * 60)

    # 1. State accuracy
    osl_acc = np.mean(osl_remapped == true_hard[:T_common])
    nj_acc = np.mean(nj_remapped == true_hard)
    print(f"\nState Accuracy (Hungarian match):")
    print(f"  osl-dynamics:  {osl_acc:.3f}")
    print(f"  neurojax:      {nj_acc:.3f}")

    # 2. Per-state Dice
    osl_gamma_remapped = osl_gamma[:T_common][:, osl_perm]
    nj_gamma_remapped = nj_gamma[:, nj_perm]

    osl_dice = dice_per_state(true_states_oh[:T_common], osl_gamma_remapped, n_states)
    nj_dice = dice_per_state(true_states_oh, nj_gamma_remapped, n_states)

    print(f"\nPer-State Dice (mean):")
    print(f"  osl-dynamics:  {osl_dice.mean():.3f}  {np.round(osl_dice, 3)}")
    print(f"  neurojax:      {nj_dice.mean():.3f}  {np.round(nj_dice, 3)}")

    # 3. Transition matrix correlation
    # Reorder rows/cols to match ground truth
    true_trans = np.zeros((n_states, n_states))
    for t in range(len(true_hard) - 1):
        true_trans[true_hard[t], true_hard[t + 1]] += 1
    true_trans /= true_trans.sum(axis=1, keepdims=True) + 1e-10

    osl_trans_r = osl_trans[np.ix_(osl_perm, osl_perm)]
    nj_trans_r = nj_trans[np.ix_(nj_perm, nj_perm)]

    osl_trans_corr = correlation_matrix(true_trans, osl_trans_r)
    nj_trans_corr = correlation_matrix(true_trans, nj_trans_r)

    print(f"\nTransition Matrix Correlation:")
    print(f"  osl-dynamics:  {osl_trans_corr:.4f}")
    print(f"  neurojax:      {nj_trans_corr:.4f}")

    # 4. Means correlation (per state)
    osl_means_r = osl_means[osl_perm]
    nj_means_r = nj_means[nj_perm]

    osl_mean_corrs = [np.corrcoef(true_means[s], osl_means_r[s])[0, 1] for s in range(n_states)]
    nj_mean_corrs = [np.corrcoef(true_means[s], nj_means_r[s])[0, 1] for s in range(n_states)]

    print(f"\nState Means Correlation (mean across states):")
    print(f"  osl-dynamics:  {np.nanmean(osl_mean_corrs):.4f}")
    print(f"  neurojax:      {np.nanmean(nj_mean_corrs):.4f}")

    # 5. Speed
    print(f"\nTraining Time:")
    print(f"  osl-dynamics:  {osl_time:.1f}s")
    print(f"  neurojax:      {nj_time:.1f}s")

    # ---- Plots ----
    fig, axes = plt.subplots(4, 1, figsize=(16, 14), gridspec_kw={"hspace": 0.35})

    # (a) State timecourse comparison (first 2000 samples)
    T_plot = 2000
    ax = axes[0]
    ax.plot(true_hard[:T_plot], alpha=0.5, label="Ground Truth", linewidth=0.8)
    ax.plot(nj_remapped[:T_plot], alpha=0.7, label="neurojax", linewidth=0.8)
    ax.plot(osl_remapped[:T_plot], alpha=0.5, label="osl-dynamics", linewidth=0.8, linestyle="--")
    ax.set_ylabel("State")
    ax.set_xlabel("Time (samples)")
    ax.set_title("(a) State Assignments (first 2000 samples)")
    ax.legend(loc="upper right")

    # (b) Transition matrices
    ax1 = axes[1]
    im_data = np.concatenate([true_trans, osl_trans_r, nj_trans_r], axis=1)
    im = ax1.imshow(im_data, aspect="auto", cmap="Blues", vmin=0)
    ax1.set_title("(b) Transition Matrices: Ground Truth | osl-dynamics | neurojax")
    ax1.set_yticks(range(n_states))
    for i, label in enumerate(["True", "OSL", "NJ"]):
        ax1.text(i * n_states + n_states / 2 - 0.5, -0.8, label, ha="center", fontsize=10)
    plt.colorbar(im, ax=ax1, shrink=0.8)

    # (c) Dice per state
    ax2 = axes[2]
    x = np.arange(n_states)
    w = 0.35
    ax2.bar(x - w / 2, osl_dice, w, label="osl-dynamics", alpha=0.8)
    ax2.bar(x + w / 2, nj_dice, w, label="neurojax", alpha=0.8)
    ax2.set_xlabel("State (reordered)")
    ax2.set_ylabel("Dice Coefficient")
    ax2.set_title("(c) Per-State Dice Overlap with Ground Truth")
    ax2.legend()
    ax2.set_ylim(0, 1.1)

    # (d) LL convergence (neurojax only — osl uses different loss scale)
    ax3 = axes[3]
    ax3.plot(history, "o-", label="neurojax LL")
    ax3.set_xlabel("Epoch")
    ax3.set_ylabel("Log-Likelihood")
    ax3.set_title("(d) neurojax Training Convergence")
    ax3.legend()

    plt.suptitle(
        f"HMM Comparison: neurojax (JAX) vs osl-dynamics (TF)\n"
        f"Accuracy — NJ: {nj_acc:.3f}, OSL: {osl_acc:.3f}  |  "
        f"Speed — NJ: {nj_time:.1f}s, OSL: {osl_time:.1f}s",
        fontsize=13,
    )
    plt.savefig("hmm_comparison.png", dpi=150, bbox_inches="tight")
    print(f"\nPlot saved to hmm_comparison.png")


if __name__ == "__main__":
    main()
